GET http://localhost:8080/api/monsters

###
//shouldn't work
GET http://localhost:8080/api/monsters/viewAll

###
GET http://localhost:8080/api/monsters/viewAll
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJNb25zdGVyQmFzaCIsInN1YiI6ImJtYWRyZWxsMCIsInJvbGVzIjpbeyJhdXRob3JpdHkiOiJST0xFX2JtYWRyZWxsMCJ9XSwidXNlcklkIjoxLCJleHAiOjE2NzI4NDg4NzZ9.3OnOeUIpt1HRV_ohlDT13-2eA8LV1jIgF0L3jaGuTjc

###
//user login
POST http://localhost:8080/api/security/login
Content-Type: application/json

{
    "username": "bmadrell0",
    "password": "password"
}

###
POST http://localhost:8080/api/security/login
Content-Type: application/json

{
    "username":    ,
    "password": 
}