GET http://localhost:8080/api/monsters

###
//shouldn't work
GET http://localhost:8080/api/monsters/viewAll

###
GET http://localhost:8080/api/monsters/viewAll
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJNb25zdGVyQmFzaCIsInN1YiI6ImJtYWRyZWxsMCIsInJvbGVzIjpbeyJhdXRob3JpdHkiOiJST0xFX2JtYWRyZWxsMCJ9XSwidXNlcklkIjoxLCJleHAiOjE2NzI4NDg4NzZ9.3OnOeUIpt1HRV_ohlDT13-2eA8LV1jIgF0L3jaGuTjc

###
//user login
POST http://localhost:8080/api/security/login
Content-Type: application/json

{
    "username": "bmadrell0",
    "password": "password"
}

###
POST http://localhost:8080/api/security/login
Content-Type: application/json

{
    "username":    ,
    "password": 
}

###
GET http://localhost:8080/api/weather/viewAll

###
GET http://localhost:8080/api/weather/2

###
POST http://localhost:8080/api/add/weather 
Content-Type: application/json

{
    "weatherName": "Wind",
    "weatherImage": "blow",
    "affinityId": "4"
}

###
PUT http://localhost:8080/api/edit/weather/2
Content-Type: application/json

{
    "weatherId": "2",
    "weatherName": "sand",
    "weatherImage": "sandy",
    "affinityId": "4"
}

###
DELETE http://localhost:8080/api/delete/weather/7


