GET http://localhost:8080/api/monsters

###
//shouldn't work
GET http://localhost:8080/api/monsters/viewAll

###
GET http://localhost:8080/api/monsters/viewAll
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJNb25zdGVyQmFzaCIsInN1YiI6ImJtYWRyZWxsMCIsInJvbGVzIjpbeyJhdXRob3JpdHkiOiJST0xFX2JtYWRyZWxsMCJ9XSwidXNlcklkIjoxLCJleHAiOjE2NzI4NDg4NzZ9.3OnOeUIpt1HRV_ohlDT13-2eA8LV1jIgF0L3jaGuTjc

###
//user login
POST http://localhost:8080/api/security/login
Content-Type: application/json

{
    "username": "bmadrell0",
    "password": "password"
}

###
POST http://localhost:8080/api/security/login
Content-Type: application/json

{
    "username":    ,
    "password": 
}

###
GET http://localhost:8080/api/weather/viewAll

###
GET http://localhost:8080/api/weather/2

###
POST http://localhost:8080/api/add/weather 
Content-Type: application/json

{
    "weatherName": "Wind",
    "weatherImage": "blow",
    "affinityId": "4"
}

###
PUT http://localhost:8080/api/edit/weather/2
Content-Type: application/json

{
    "weatherId": "2",
    "weatherName": "sand",
    "weatherImage": "sandy",
    "affinityId": "4"
}

###
DELETE http://localhost:8080/api/delete/weather/3

###

GET http://localhost:8080/api/equipment/viewAll

###
GET http://localhost:8080/api/equipment/4

###
POST http://localhost:8080/api/add/equipment
Content-Type: application/json

{
  "equipmentName": "Murder ball",
  "equipmentImage": "google2.com",
  "strength": "85",
  "affinityId": "5"

}

###
PUT http://localhost:8080/api/edit/equipment/7
Content-Type: application/json

{
  "equipmentId": "7",
  "equipmentName": "Murder sphere",
  "equipmentImage": "google3.com",
  "strength": "70",
  "affinityId": "2"

}

###
DELETE http://localhost:8080/api/delete/equipment/7

###
GET http://localhost:8080/api/monster/viewAll

###

GET http://localhost:8080/api/monster/12

###

POST http://localhost:8080/api/add/monster 
Content-Type: application/json

{
    "monsterName": "Test",
    "monsterImage": "tester",
    "power": "42",
    "elementId": "3"
}

###
PUT http://localhost:8080/api/edit/monster/12
Content-Type: application/json

{
  
    "monsterId": "12",
    "monsterName": "Test-updated",
    "monsterImage": "tester-put working",
    "power": "42",
    "elementId": "3"

}

###
DELETE http://localhost:8080/api/delete/monster/12

###
GET http://localhost:8080/api/location/viewAll

###

GET http://localhost:8080/api/location/2

###

POST http://localhost:8080/api/add/location 
Content-Type: application/json

{
    "locationName": "Test",
    "locationImage": "tester.com",
    "elementId": "3"
}

###
PUT http://localhost:8080/api/edit/location/7
Content-Type: application/json

{
  
    "locationId": "7",
    "locationName": "Test-updated",
    "locationImage": "tester-put working.com",
    "elementId": "3"

}

###
DELETE http://localhost:8080/api/delete/location/7

